import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().default(3000),
  DATABASE_URL: Joi.string().required(),
  REDIS_URL: Joi.string().required(),
  APP_PROCESS: Joi.string().valid('api', 'worker').optional(),
  FEISHU_BASE_URL: Joi.string().uri().default('https://open.feishu.cn/open-apis'),
  FEISHU_EVENT_MODE: Joi.string().valid('webhook', 'ws').default('webhook'),
  FEISHU_WS_EVENT_TYPES: Joi.string().allow('').default('im.message.receive_v1,im.chat.member.bot.added_v1,card.action.trigger'),
  FEISHU_APP_ID: Joi.string().allow('').required(),
  FEISHU_APP_SECRET: Joi.string().allow('').required(),
  FEISHU_VERIFICATION_TOKEN: Joi.string().allow('').required(),
  FEISHU_ENCRYPT_KEY: Joi.string().allow('').required(),
  PI_MONO_PROVIDER: Joi.string().allow('').default('bailian'),
  PI_MONO_MODEL: Joi.string().allow('').default('kimi-k2.5'),
  PI_MONO_THINKING_LEVEL: Joi.string().valid('off', 'minimal', 'low', 'medium', 'high', 'xhigh').default('off'),
  PI_MONO_WORKDIR: Joi.string().allow('').default('/workspace'),
  PI_MONO_AGENT_DIR: Joi.string().allow('').default('/workspace/.pi-agent'),
  BAILIAN_BASE_URL: Joi.string().uri().default('https://dashscope.aliyuncs.com/compatible-mode/v1'),
  DASHSCOPE_API_KEY: Joi.string().allow('').optional(),
  PI_MONO_BASE_URL: Joi.string().allow('').optional(),
  PI_MONO_API_KEY: Joi.string().allow('').optional(),
  PI_MONO_CALLBACK_SECRET: Joi.string().allow('').optional(),
  OPENAI_API_KEY: Joi.string().allow('').optional(),
  ANTHROPIC_API_KEY: Joi.string().allow('').optional(),
  GEMINI_API_KEY: Joi.string().allow('').optional(),
  GROQ_API_KEY: Joi.string().allow('').optional(),
  OPENROUTER_API_KEY: Joi.string().allow('').optional(),
  ADMIN_JWT_SECRET: Joi.string().required(),
  PUBLIC_BASE_URL: Joi.string().uri().required(),
  CONFIRMATION_TTL_MINUTES: Joi.number().default(30),
  AGENT_RUN_TIMEOUT_SECONDS: Joi.number().default(1800),
  DIGEST_TIMEZONE: Joi.string().default('Asia/Shanghai'),
  DIGEST_DAILY_CRON: Joi.string().default('0 10 * * 1-5'),
  DIGEST_WEEKLY_CRON: Joi.string().default('0 17 * * 5'),
  DIGEST_FOLDER_SCAN_LIMIT: Joi.number().default(500),
  DIGEST_DOC_CONTENT_LIMIT: Joi.number().default(20),
  DIGEST_BITABLE_ROW_LIMIT: Joi.number().default(2000),
});
